// Header file for the ColorMatch application
// This file is generated by the ColorMatch Application in Learn Mode

// Calibration data
sensorData sdBlack = { 7770, 6720, 8840 };
sensorData sdWhite = { 54390, 51740, 69490 };

// Color Table for matching
typedef struct
{
  char    name[10];  // color name 8+nul
  colorData rgb;    // RGB value
} colorTable;

colorTable ct[] = 
{
  {"BRANCO",    {255, 253 , 255 } }, 
  {"VERMELHO",  {141, 33  , 38  } },
  {"VERDE",     {83 , 143 , 86  } }, 
  {"AZUL",      {41 , 92  , 160 } }, 
  {"LARANJA",   {236, 102 , 70  } },
  {"PRETO",     {0  , 0   , 0   } } 
};
	
